openapi: 3.0.1
info:
  title: BORGA
  description: "A Board Games Application"
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
tags:
  - name: Board Games Application
    description: A board games personal library.
    externalDocs:
      description: Based on
      url: https://api.boardgameatlas.com/
paths:
  /api/games:
    get:
      tags:
        - Games
      summary: Find a game by query
      description: Uses Board Game Atlas API to find games by providing a query.
      parameters:
        - name: top
          in: query
          description: Query to get the top N games by popularity
          required: false
          schema:
            type: string
            example: "?top=20"
      parameters:
        - name: id
          in: query
          description: Query to get a game by ID
          required: false
          schema:
            type: string
            example: "?id=TAAifFP590"
      parameters:
        - name: name
          in: query
          description: Query to get a list of games related to the name provided
          required: false
          schema:
            type: string
            example: "?name=catan"
      responses:
        200:
          description: Game Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Game"
        200:
          description: Games Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GamesList"
        503:
          description: External API Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
        404:
          description: Game not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
        500:
        description: Unexpected response from external API
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
  /api/groups:
    get:
      tags:
        - Groups
      summary: Get all groups
      description: List all existing groups
      security:
      - bearerAuth: []
      responses:
        200:
          description: Groups List
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GroupsList"
        403: 
          description: Not authorized to list all groups
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
    get:
      tags:
        - Groups
      summary: Get group information
      description: Get a group by its ID
      security:
      - bearerAuth: []
      parameters:
        - name: id
          in: params
          description: ID of the group to search for
          required: false
          schema:
            type: string
            example: "/groups/2"
      responses:
        200:
          description: Group Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
        403: 
          description: Not authorized to list a group
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
        404: 
          description: Group does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
    delete:
      tags:
        - Groups
      summary: Delete a group
      description: Delete a group by its ID
      security:
      - bearerAuth: []
      parameters:
        - name: id
          in: params
          description: ID of the group to delete
          required: false
          schema:
            type: string
            example: "/groups/2"
      responses:
        200:
          description: Group Deleted
        403: 
          description: Not authorized to delete another users group 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
        400:
          description: Invalid token or missing parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
        404: 
          description: Group does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
    post:
      tags:
        - Groups
      summary: Create new group
      description: Creates a new group with provided information
      security:
      - bearerAuth: []
      requestBody:
        description: Information to initialize the new group with
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GroupInit"
      responses:
        201:
          description: Group Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ID"
        400:
          description: Invalid token or missing parameters
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/AppError"
        403: 
          description: Not authorized to create a group
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
    put:
      tags: 
        - Groups
      summary: Update information about a group  
      description: Update information about an existing group
      security:
      - bearerAuth: []
      requestBody:
        description: New Information to update the new group with
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GroupInit"
    responses:
      200:
        description: The group has been updated successfully
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/ID"
      400:
        description: Invalid group details or token or missing parameters
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
      403: 
        description: Not authorized to delete another users group 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppError"
      404: 
        description: Group does not exist
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppError"
  /api/groups/games:
    post:
      tags:
        - Group Games
      summary: Add a game to a group
      description: Adds a game to a group by it's ID
      security:
      - bearerAuth: []
      parameters:
        - name: group_id
          in: params
          description: ID of the group to add the game to
          required: true
          schema:
            type: int
          example: "groups/1/"
      requestBody:
        description: ID of the game to add to the group
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ID"
      responses:
        200:
          description: Game Added to Group successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
        400:
          description: Invalid token or missing parameters
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/AppError"
        403: 
            description: Not authorized to add a game to another users group
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/AppError"
        404: 
          description: Game or group does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
    delete:
      tags:
        - Group Games
      summary: Delete a game from a group
      description: Deletes a game from a group by it's ID
      security:
      - bearerAuth: []
      parameters:
        - name: group_id
          in: params
          description: ID of the group to add the game to
          required: true
          schema:
            type: int
          example: "groups/1/"
        - name: game_id
          in: params
          description: ID of the game to remove from group
          required: true
          schema:
            type: string
          example: "groups/1/games/TAAifFP590"
      responses:
        200:
          description: Game deleted successfuly from group
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
        400:
          description: Invalid token or missing parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
        403: 
            description: Not authorized to delete a game to another users group
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/AppError"
        404: 
          description: Group does not exist or group does not contain the specified game
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/AppError"
  /api/users:
    get:
      tags:
        - Users
      summary: Get information about a user
      description: Get information about a user given it's username
      parameters:
        - name: username
          in: params
          description: Username for the user to retrieve information about
          required: true
          schema:
            type: string
            example: "users/Manuel"
      responses:
        200: 
          description: Got user information
          content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserData" 
        400:
          description: Missing parameters
          application/json:
          schema:
            $ref: "#/components/schemas/AppError" 
        404:
          description: User does not exist
          application/json:
            schema:
              $ref: "#/components/schemas/AppError" 
    post:
      tags:
        - Users
      summary: Create a new user
      description: Creates a new user with the information given
      requestBody:
        description: Information to initialize the new user with
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserData"
      responses:
        201:
          description: User Created Successfuly
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token" 
        400:
          description: Missing parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
        409: 
          description: User already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
  /api/users/groups:
    post: 
      tags:
        - User Groups
      summary: Adds a group reference to a user
      description: References an existing group to an existing user
      security:
      - bearerAuth: []
      requestBody:
        description: ID of the group to add to user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ID"
      responses:
        200:
          description: Group reference added to user (identified by its token)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Invalid token or missing parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
        404: 
          description: Group does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
        409:
          description: User already has this group
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
    delete: 
      tags:
        - User Groups
      summary: Deletes a group reference to a user
      description: Removes a reference of a group from an existing user (identified by its token)
      security:
      - bearerAuth: []
      requestBody:
        description: ID of the group to remove from user groups
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ID"
      responses:
        200:
          description: Group reference removed from user groups
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Invalid token or missing parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
        404: 
          description: User doesn't have a reference to this group inside his groups
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppError"
components:
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
  schemas:
    Token: 
      type: object
      description: An access token generated upon user creation
      properties:
        token: 
          type: string
          description: An auth token used to identify a user
          example: "3c184965-cc3e-44d5-a5b1-b36ae47819fa"
    GamesList:
      type: array
      description: A list of Games
        items:
          $ref: "#/components/schemas/Game"
    AppError:
      type: object
      description: Application error
      required:
        - internal_code
        - http_code
        - message
      properties:
        internal_code:
          type: number
          format: int32
          description: Internal error code
          example: 0
        http_code:
          type: number
          format: int32
          description: Http error code
          example: 0
        message:
          type: string
          description: Error descriptive message
          example: Error message here
    GroupInit:
      type: object
      description: Group initialization schema
      required: 
        - name
        - description
      properties: 
        name:
          type: string
        description: 
          type: string
    Group:
      type: object
      description: A group of games
      required: 
        - owner
        - name
        - description
        - games
      properties: 
        owner: 
          type: string
        name:
          type: string
        description:
          type:  string
        games: 
          type: array
          items: 
            type: string
            description: Name of a game
    GroupsList:
      type: object
      description: Response with a list of groups
      properties:
        groups:
          type: array
          items:
            $ref: "#/components/schemas/Group"
    ID:
      type: object
      description: Game ID
      required:
        - id
      properties:
        id:
          type: string
          example: TAAifFP590
    Game:
      type: object
      description: Game data
      required:
        - id
        - name
        - url
        - price
        - min_age
        - min_players
        - max_players
      properties:
        id:
          type: string
          description: Game ID
          example: TAAifFP590
        name:
          type: string
          description: Game Name
          example: Root
        url:
          type: string
          description: Game link with more information
          example: https://www.boardgameatlas.com/game/TAAifFP590/root
        price:
          type: string
          description: Price of the game
          example: 47.99
        min_age:
          type: int
          description: Minimum age for this game
          format: date
          example: 10
        min_players:
          type: int
          description: Minimum players needed for this game
          example: 2
        max_players:
          type: int
          description: Maximum players for this game
          example: 4
    User:
      type: object
      required: 
        - username
      properties: 
        username: 
          type:
            - string
            - int
          example: "Zé"
